### ISSUE TITLE
Design the backend architecture using GitHub APIs

### ISSUE THREAD

**Issue by rkaneko** [rkaneko/ambient#25]
- use GitHub as a backend
  - use GraphQL API??

**Comment by rkaneko** [comment]
### Requirements

#### Must
- [ ] API for fetching files (including file names, created datetime, updated datetime and so on) in the repository

**Comment by rkaneko** [comment]
### Decision

- use GitHub **REST** APIs v3

example
https://github.com/rkaneko/github-graphql/blob/6601703f646691fefa86f1886bb93622ce5ea0cd/src/js/rest/get-branch-content.js

#### Why don't we use **GraphQL** APIs

GraphQL is much useful, but I don't know how to get a git blob data like using a [REST contents API](https://developer.github.com/v3/repos/contents/). If this is possible, I'll try to use GraphQL APIs.

**Comment by rkaneko** [comment]
### Notes

I want that ambient has only static files like html, css, JavaScript, JSON and so on.
So, I'd use GitHub APIs without authentication.

### TODO

Must investigate

- [ ] Can i get files and directories via APIs without auth?
  - Yes. Use a contents API https://api.github.com/repos/rkaneko/ambient/contents .
- [ ] Can I get a commit information for files?

**Comment by rkaneko** [comment]
My research is done.
